volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  front-tier:
  back-tier:

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
      
  prometheus:
    image: prom/prometheus
    container_name: Prometheus
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prometheus-data:/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml

  grafana:
    container_name: Grafana
    image: grafana/grafana
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=redis-datasource
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    networks:
      - back-tier
      - front-tier
    restart: always

  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 52000:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Projet
      MYSQL_USER: root

  node:
    image: node
    container_name: Node
    build:
      context: .
    ports:
      - 3001:3001
    expose:
      - "3001"